services:
    development:
        container_name: development
        build: .
        mem_limit: 2G
        # nosemgrep
        privileged: true
        environment:
            - AUTHORIZED_PUBLIC_KEYS=${SSH_PUBLIC_KEY}
            - USER_GROUPS=user
        tmpfs:
            - /tmp:exec
        ports:
            - "127.0.0.1:8022:22"
